openapi: 3.0.0
info:
  title: Test2
  description: This is a generic API definition for manipulation of StockData resources. It contains basic CRUD operations for StockData resources.
  version: 1.0
paths:
  /StockData:
    get:
      summary: Retrieve StockData resources.
      description: Retrieve a bunch of StockData resources. Specifiy example resource as body payload.
      operationId:
      responses:
        200:
          description: Get an array of StockData resources.
    post:
      summary: Create new StockData resource.
      description: Create a new StockData resource. Specify payload within request body.
      operationId:
      requestBody:
        description: The payload of resource StockData to create.
        content:
          application/json:
            schema:
              $ref: '#/components/schema/AnyType'
      responses:
        201:
          description: Get the newly created StockData resource.
  /StockData/{id}:
    get:
      summary: Retrieve a StockData resource.
      description: Retrieve an already existing StockData resource having the specified id.
      operationId:
      responses:
        200:
          description: StockData resource having specified id.
          content:
            application/json:
              schema:
                 $ref: '#/components/schema/AnyType'
    put:
      summary: Update a StockData resource.
      description: Update an already existing StockData resource having the specified id.
      operationId:
      requestBody:
        description: The payload of resource StockData to update.
        content:
          application/json:
            schema:
              $ref: '#/components/schema/AnyType'
      responses:
        200:
          description:
          content:
            application/json:
              schema:
    delete:
      summary: Delete a StockData resource.
      description: Remove an existing StockData resource having the specified id.
      operationId:
      responses:
        204:
          description: Resource StockData with specified id has been removed.
    parameters:
      - name: id
        in: path
        description: Id of resource
        required: true
        schema:
          type: string
components:
  schemas:
    AnyType:
